# Generated by Django 6.0.2 on 2026-02-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('formation', 'Formation professionnelle'), ('langue', 'Cours de langue')], max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=30)),
                ('formation', models.CharField(blank=True, choices=[('Maintenance', 'Maintenance'), ('Marketing Digital', 'Marketing Digital'), ('Comptabilité', 'Comptabilité')], max_length=50, null=True)),
                ('langue', models.CharField(blank=True, choices=[('Français', 'Français'), ('Anglais', 'Anglais'), ('Chinois', 'Chinois'), ('Italien', 'Italien')], max_length=50, null=True)),
                ('niveau', models.CharField(blank=True, max_length=50, null=True)),
                ('modalite', models.CharField(choices=[('Présentiel', 'Présentiel'), ('En ligne', 'En ligne'), ('Hybride', 'Hybride')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
