# Generated by Django 6.0.2 on 2026-02-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='type',
        ),
    ]
