# Generated by Django 6.0.2 on 2026-02-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='formation',
            field=models.CharField(blank=True, choices=[('Maintenance', 'Maintenance'), ('Marketing Digital', 'Marketing Digital'), ('Comptabilité', 'Comptabilité'), ('Développement Web', 'Développement Web'), ('Développement Mobile', 'Développement Mobile'), ('Secrétariat Bureautique', 'Secrétariat Bureautique'), ('Secrétariat Comptable', 'Secrétariat Comptable'), ('Comptabilité et Gestion', 'Comptabilité et Gestion'), ('Montage Audio Visuel', 'Montage Audio Visuel'), ('Graphisme de Production', 'Graphisme de Production'), ('Maintenance Informatique', 'Maintenance Informatique')], max_length=50, null=True),
        ),
    ]
