# Generated by Django 6.0.2 on 2026-03-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_inscription_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='formation',
            field=models.CharField(blank=True, choices=[('maintenance', 'Maintenance'), ('marketing-digital', 'Marketing Digital'), ('comptabilite', 'Comptabilité'), ('dev-web', 'Développement Web'), ('dev-mobile', 'Développement Mobile'), ('secretaire-bureautique', 'Secrétariat Bureautique'), ('secretaire-comptable', 'Secrétariat Comptable'), ('compta-gestion', 'Comptabilité et Gestion'), ('montage-audio-visuel', 'Montage Audio Visuel'), ('graphisme', 'Graphisme de Production'), ('maintenance-info', 'Maintenance Informatique')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='langue',
            field=models.CharField(blank=True, choices=[('francais', 'Français'), ('anglais', 'Anglais'), ('chinois', 'Chinois'), ('italien', 'Italien')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='modalite',
            field=models.CharField(choices=[('presentiel', 'Présentiel'), ('en-ligne', 'En ligne'), ('hybride', 'Hybride')], max_length=20),
        ),
    ]
